### ISSUE TITLE
Consulta acerca de la práctica 7

### ISSUE THREAD

**Issue by ccolivares** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo_n#1]
Trabajando en la práctica en grupo de DSI mi grupo y yo nos hemos dado cuenta de que tal y como están planteadas las clases dependen unas de otras para declararse entonces esto es un problema a la hora de inicializar objetos. 

Un ejemplo podría ser que un género musical pide una lista de canciones, pero las canciones piden pertenecer a algún género musical, al intentar declarar estos objetos habrán conflictos. 

También nos encontramos que un artista pide tener un conjunto de grupos al que pertenece, pero ¿Al ser un solista esta característica debería estar vacía?

@esegredo @amarrerod

**Comment by esegredo** [comment]
Hola, buenas.

No es ningún problema si tu diseño es adecuado. Se denomina composición de objetos.

El hecho de que un género pida una lista de canciones para construirse y que una canción necesite uno o varios géneros para construirse es un asunto de tu diseño.

Saludos.
@ccolivares @alu0101100586 @alu0101101507 @amarrerod
